/**
 * India trade language → index tokens / chapter boosts.
 * Tuned for Neo Logistics cargo mix (Cochin / Chennai CHA desk).
 */
export const INDIA_ALIASES: Record<string, string[]> = {
  // Steel / metals
  hrc: ["hot-rolled", "flat-rolled", "coils", "width of 600"],
  crc: ["cold-rolled", "flat-rolled", "coils"],
  "hr plate": ["hot-rolled", "flat-rolled", "plates"],
  "hr coil": ["hot-rolled", "flat-rolled", "coils", "width of 600"],
  "cr coil": ["cold-rolled", "flat-rolled", "coils"],
  "gi sheet": ["galvanised", "galvanized", "zinc", "coated"],
  "gi coil": ["galvanised", "galvanized", "zinc", "coated", "coils"],
  "galvalume": ["aluminium", "zinc", "coated", "flat-rolled"],
  "gl coil": ["aluminium", "zinc", "coated", "flat-rolled", "coils"],
  "tmt bars": ["bars and rods", "iron", "steel", "hot-rolled"],
  "ms plate": ["flat-rolled", "non-alloy steel", "plates"],
  "stainless coil": ["stainless", "flat-rolled", "coils"],
  "billets": ["semi-finished", "iron", "steel"],
  "slabs": ["semi-finished", "iron", "steel"],

  // Cashew / agri (Cochin specialty)
  "cashew kernel": ["cashew kernel", "cashew nuts", "shelled"],
  "cashew kernels": ["cashew kernel", "cashew nuts", "shelled"],
  "raw cashew": ["cashew nuts", "in shell"],
  "rcn": ["cashew nuts", "in shell"],
  "w180": ["cashew kernel", "whole"],
  "w210": ["cashew kernel", "whole"],
  "w240": ["cashew kernel", "whole"],
  "w320": ["cashew kernel", "whole"],
  "w450": ["cashew kernel", "whole"],
  "sw320": ["cashew kernel", "whole"],
  "cashew broken": ["cashew kernel", "broken"],
  "cashew splits": ["cashew kernel", "broken"],
  "cashew pieces": ["cashew kernel", "broken"],
  "pepper": ["pepper of the genus piper"],
  "black pepper": ["pepper of the genus piper"],
  "cardamom": ["cardamoms"],
  "tea": ["tea", "flavoured"],
  "rubber": ["natural rubber"],
  "rss": ["natural rubber"],
  "centrifuged latex": ["natural rubber", "latex"],

  // Seafood
  vannamei: ["vannamei shrimp", "shrimps", "prawns"],
  "black tiger": ["black tiger shrimp", "shrimps"],
  "indian white": ["indian white shrimp", "shrimps"],
  "flower shrimp": ["flower shrimp", "shrimps"],
  prawns: ["shrimps", "prawns"],
  shrimp: ["shrimps", "prawns"],
  "iqf shrimp": ["shrimps", "prawns", "frozen"],
  "cooked shrimp": ["shrimps", "prawns"],
  "headless shrimp": ["shrimps", "prawns"],
  "hlso": ["shrimps", "prawns"],
  "pd shrimp": ["shrimps", "prawns"],
  "squid": ["cuttle fish", "squid"],
  "cuttlefish": ["cuttle fish"],

  // Cement / minerals / Neo desk mix
  "portland cement": ["portland cement"],
  "white cement": ["white portland cement", "portland cement"],
  "white cement clinker": ["cement clinkers"],
  "cement clinker": ["cement clinkers"],
  "opc cement": ["portland cement"],
  "ppc cement": ["portland cement"],
  "clinker": ["cement clinkers"],
  "quick lime": ["quicklime"],
  quicklime: ["quicklime"],
  "gypsum plaster": ["calcined", "gypsum"],
  "sodium chlorate": ["chlorates", "sodium"],
  hydrafiber: ["mechanical wood pulp"],
  "hydra fiber": ["mechanical wood pulp"],
  "titanium dioxide": ["titanium dioxide"],
  tio2: ["titanium dioxide"],
  "vae dispersion": ["vinyl acetate", "aqueous dispersion"],
  "vae polymer": ["vinyl acetate", "aqueous dispersion"],
  "kraft pulp": ["chemical wood pulp", "coniferous"],
  "bleached kraft": ["chemical wood pulp", "bleached", "coniferous"],
  "unbleached kraft": ["chemical wood pulp", "unbleached", "coniferous"],
  "artificial grass": ["turf", "man-made textile"],
  "artificial turf": ["turf", "man-made textile"],
  "pvc foam board": ["cellular", "polymers of vinyl chloride"],
  "coco peat": ["coir pith"],
  cocopeat: ["coir pith"],
  "coir pith": ["coir pith"],
  "vermi compost": ["animal or vegetable fertilisers"],
  vermicompost: ["animal or vegetable fertilisers"],
  "spun pipe": ["spun pipe", "cast iron"],
  "cast iron pipe": ["spun pipe", "cast iron"],
  "iron ore fines": ["iron ores", "non-agglomerated"],
  "iron ore lumps": ["iron ores", "non-agglomerated"],
  "pellets": ["iron ores", "agglomerated"],

  // Autos / industrial
  lcv: ["goods vehicles", "motor vehicles for the transport of goods"],
  "goods vehicle": ["goods vehicles", "motor vehicles for the transport of goods"],
  "three wheeler": ["vehicles", "transport of persons"],
  "sanitary ware": ["ceramic sinks", "wash basins", "sanitary"],
  "wash basin": ["ceramic sinks", "wash basins"],
  "toilet seat": ["lavatory seats", "covers"],
  "bathroom cabinet": ["furniture of plastics"],
  "glass mirror": ["unframed", "mirrors"],
  gasket: ["gaskets"],
  "gasket lubricant": ["lubricating preparations"],

  // Polymers / chem
  "pp granules": ["polypropylene", "primary forms"],
  "pp resin": ["polypropylene", "primary forms"],
  "hdpe granules": ["polyethylene", "primary forms"],
  "ldpe granules": ["polyethylene", "primary forms"],
  "lldpe": ["polyethylene", "primary forms"],
  "pvc resin": ["polyvinyl chloride", "primary forms"],
  methanol: ["methanol", "methyl alcohol"],
  "caustic soda": ["sodium hydroxide"],
  "sulphuric acid": ["sulphuric acid"],

  // Electronics / energy
  "solar module": ["photovoltaic", "solar"],
  "solar panel": ["photovoltaic", "solar"],
  "li-ion": ["lithium", "electric accumulators"],
  "lithium ion": ["lithium", "electric accumulators"],
  "inverter": ["static converters"],
  jewellery: ["jewellery", "articles of jewellery"],
  jewelry: ["jewellery", "articles of jewellery"],
  paracetamol: ["paracetamol", "medicaments", "containing"],
  acetaminophen: ["paracetamol", "medicaments"],

  // Textiles
  "cotton yarn": ["cotton yarn"],
  "cotton fabric": ["woven fabrics of cotton"],
  "denim": ["woven fabrics of cotton"],
  "knit fabric": ["knitted or crocheted fabrics"],
  "t-shirt": ["t-shirts", "knitted"],
  "tee shirt": ["t-shirts", "knitted"],
};

export const INDIA_CHAPTER_HINTS: Array<{ re: RegExp; chapter: string; bonus: number }> = [
  { re: /\b(cashew|w180|w210|w240|w320|rcn)\b/i, chapter: "08", bonus: 6 },
  { re: /\b(coffee)\b/i, chapter: "09", bonus: 6 },
  { re: /\b(pepper|cardamom|tea)\b/i, chapter: "09", bonus: 4 },
  { re: /\b(shrimp|prawn|vannamei|seafood|hlso|iqf)\b/i, chapter: "03", bonus: 5 },
  { re: /\b(squid|cuttlefish)\b/i, chapter: "03", bonus: 4 },
  {
    re: /\b(hrc|crc|hot.?rolled|cold.?rolled|gi\s?(sheet|coil)|galvalume|tmt|steel\s+coil|ms\s+plate)\b/i,
    chapter: "72",
    bonus: 5,
  },
  { re: /\b(cement|portland|clinker|opc|ppc|quick\s*lime|gypsum)\b/i, chapter: "25", bonus: 5 },
  { re: /\b(cotton\s+(fabric|yarn)|woven\s+cotton|denim)\b/i, chapter: "52", bonus: 4 },
  { re: /\b(t-?shirts?|tee\s*shirts?)\b/i, chapter: "61", bonus: 4 },
  { re: /\b(polypropylene|pp\s+(resin|granule)|hdpe|ldpe|lldpe|pvc\s+resin|vae|vinyl\s+acetate)\b/i, chapter: "39", bonus: 5 },
  { re: /\b(methanol|methyl\s+alcohol|caustic\s+soda|sulphuric)\b/i, chapter: "29", bonus: 4 },
  { re: /\b(sodium\s+chlorate)\b/i, chapter: "28", bonus: 6 },
  { re: /\b(titanium\s+dioxide|tio2)\b/i, chapter: "32", bonus: 5 },
  { re: /\b(iron\s+ore|pellets)\b/i, chapter: "26", bonus: 5 },
  { re: /\b(lcv|goods\s+vehicle|truck)\b/i, chapter: "87", bonus: 4 },
  { re: /\b(sanitary\s+ware|wash\s+basin|lavatory)\b/i, chapter: "69", bonus: 4 },
  { re: /\b(kraft\s+pulp|hydrafiber|wood\s+pulp)\b/i, chapter: "47", bonus: 5 },
  { re: /\b(artificial\s+(grass|turf))\b/i, chapter: "57", bonus: 5 },
  { re: /\b(coco\s*peat|coir\s+pith)\b/i, chapter: "53", bonus: 5 },
  { re: /\b(spun\s+pipe|cast\s+iron\s+pipe)\b/i, chapter: "73", bonus: 5 },
  { re: /\b(gasket)\b/i, chapter: "40", bonus: 4 },
  { re: /\b(vermi\s*-?\s*compost)\b/i, chapter: "31", bonus: 5 },
  { re: /\b(jewellery|jewelry)\b/i, chapter: "71", bonus: 6 },
  { re: /\bfurniture\b/i, chapter: "94", bonus: 5 },
  { re: /\b(natural\s+rubber|rss|latex)\b/i, chapter: "40", bonus: 5 },
  { re: /\b(smartphone|mobile\s+phone|cellular)\b/i, chapter: "85", bonus: 4 },
  { re: /\b(laptop|notebook\s+computer)\b/i, chapter: "84", bonus: 4 },
  { re: /\b(solar\s+panel|photovoltaic)\b/i, chapter: "85", bonus: 4 },
  { re: /\b(lithium[\s-]?ion|li[\s-]?ion).{0,40}(batter|accumulator)/i, chapter: "85", bonus: 6 },
  { re: /\b(electric\s+motor|induction\s+motor)\b/i, chapter: "85", bonus: 5 },
  { re: /\b(paracetamol|acetaminophen|medicament)\b/i, chapter: "30", bonus: 6 },
];
